spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_app
spring.datasource.username=ella
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Formatea el JSON de salida automáticamente
spring.jackson.serialization.indent_output=true
server.port=8083