spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_app
spring.datasource.username=ella
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Formatea el JSON de salida automáticamente
spring.jackson.serialization.indent_output=true
server.port=8083
# JWT
security.jwt.secret=energia_demo_backend_jwt_secret_2026_secure_key_123456
security.jwt.expiration-ms=86400000